CREATE TABLE CARTS (
    ID            BINARY(16) DEFAULT (UUID_TO_BIN(UUID())) PRIMARY KEY NOT NULL,
    DATE_CREATED  DATE DEFAULT (CURDATE()) NOT NULL
);

CREATE TABLE CART_ITEMS (
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    CART_ID     BINARY(16) NOT NULL,
    PRODUCT_ID  BIGINT NOT NULL,
    QUANTITY    INT NOT NULL,

    CONSTRAINT UK_CART_PRODUCT UNIQUE (CART_ID, PRODUCT_ID),

    FOREIGN KEY (CART_ID) REFERENCES CARTS(ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID) ON DELETE CASCADE
);



